### PR TITLE
Fix QtCoin SetUserText

### PR DESCRIPTION
**Pull request by cielavenir**
https://github.com/rdiankov/openrave/pull/1328/commits/c11d17683d35495e4c1c3712019bfd68906b818d has typo, which prevents compilation when the machine has libcoin-dev

Why autotester works fine currently? Because jhbuild does not have libcoin-dev and qtcoin is not built.

/cc @jerasman @wkentaro @florisatmujin (I believe vision team should have libcoin-dev installed on their machine and they should be affected)

### CODE REVIEW

**Comment by cielavenir** [comment]
clarify: This affects only local build and autotester does not have meanings.

**Comment by florisatmujin** [comment]
> [c11d176](https://github.com/rdiankov/openrave/commit/c11d17683d35495e4c1c3712019bfd68906b818d) has typo, which prevents compilation when the machine has libcoin-dev
> 
> Why autotester works fine currently? Because jhbuild does not have libcoin-dev and qtcoin is not built.
> 
> /cc @jerasman @wkentaro @florisatmujin (I believe vision team should have libcoin-dev installed on their machine and they should be affected)

Yes, we use this a lot because the visualizer works better. And I just encountered the issue as well.

Thank you for fixing, I just confirmed by building locally with the branch of this PR that it works.

**Comment by yoshikikanemoto** [comment]
thanks @cielavenir

**Pull request merged**
