### PR TITLE
Fixed ComputePoseArrayDistSqr

### PR DESCRIPTION
**Pull request by cielavenir**
Usually we should use ComputePoseDistSqr, but somehow I found this function and its import was wrong...

Now it should return the same value as ComputePoseDistSqr.

### CODE REVIEW

**Comment by rdiankov** [comment]
@cielavenir `pose0` should be 7-elements, you are treating it as a 2D array here. perhaps you need a new function, or you need to test for its shape

**Comment by cielavenir** [comment]
I'm pretty sorry to have misunderstood the interface. pose0 is a pose and posearray is pose-list. I fixed it.

However, I can see major arithmetic difference from ComputePoseDistSqr. Could you check my calculation? (I would need to fix basicmath.py as well)

**Comment by cielavenir** [comment]
(basicmath.py update sent)

**Comment by cielavenir** [comment]
now that basicmath.py fix is merged, what about this one?

**Comment by rdiankov** [comment]
looks good, thanks!

**Pull request merged**
