### PR TITLE
Add virtual destructors to the classes that have virtual functions

### PR DESCRIPTION
**Pull request by lazydroid**
Classes with virtual functions must have virtual destructors, otherwise these cannot be overriden in the derived classes, leading to memory leaks, pain and suffering. While cleaning up the rest of the code base, there are a few header files from this repository the compiler complained about while building the other modules. Hence this pull request.

No visible regressions

image

### CODE REVIEW

**Comment by yoshikikanemoto** [comment]
@lazydroid why not adding the `-Werror=non-virtual-dtor` compiler option and fixing other places too?

**Comment by lazydroid** [comment]
> @lazydroid why not adding the `-Werror=non-virtual-dtor` compiler option and fixing other places too?

These small and benign changes unblock fixing other repositories, adding compiler options and fixing other places will be done in another (much bigger?) MR.

**Comment by yoshikikanemoto** [comment]
this change is ABI breaking. can you increment minor version?

**Comment by lazydroid** [comment]
了解, minor version is incremented. thank you!

**Review by yoshikikanemoto — APPROVED** [review]
@rdiankov this PR is ready.

**Comment by yoshikikanemoto** [comment]
merging since this prevents memory leaks from happening with almost zero cost.

**Comment by lazydroid** [comment]
> merging since this prevents memory leaks from happening with almost zero cost.

thank you very much!  :1st_place_medal:

**Pull request merged**
