### PR TITLE
Replace semicollons in FCL_LDFLAGS with spaces

### PR DESCRIPTION
**Pull request by woodychow**
This fixes https://github.com/rdiankov/openrave/issues/633

Regression was introduced by
https://github.com/rdiankov/openrave/pull/611

### CODE REVIEW

**Comment by ziyan** [comment]
What about this line above?

```
set(CMAKE_REQUIRED_FLAGS "${PLUGIN_COMPILE_FLAGS} ${FCL_CFLAGS_OTHER} -std=c++11 ${PLUGIN_LINK_FLAGS} ${FCL_LDFLAGS}")
```

**Comment by rdiankov** [comment]
@ziyan can you take a look again?

**Comment by cielavenir** [comment]
sorry if I say something wrong, but I suppose that Ziyan's code

```
set(CMAKE_REQUIRED_FLAGS "${PLUGIN_COMPILE_FLAGS} ${FCL_CFLAGS_OTHER} -std=c++11 ${PLUGIN_LINK_FLAGS} ${FCL_LDFLAGS}")
```

is good except that FCL_LDFLAGS's `";"` needs to be replaced with `" "`.

if you have concerns about `string(REPLACE)`, I **used to** use similar technique as https://github.com/mujin/controllerclientcpp/commit/376a48ee90075ff404885b92ce8e917d3e2ced8e .

**Comment by cielavenir** [comment]
@ziyan Sorry I have misunderstood what you mean. Your concern is addressed in https://github.com/rdiankov/openrave/pull/708/commits/18831785c536f801f1af66fffff7eb7bec60d8e8 .

**Comment by cielavenir** [comment]
as #708 is taking too much time, I fixed this branch's CMAKE_REQUIRED_FLAGS.

there are two approaches to convert list to string:

- use string(REPLACE) #640
- use [bulletrave-style](https://github.com/rdiankov/openrave/blob/master/plugins/bulletrave/CMakeLists.txt#L23) string concatenation #708

which do you like better? @rdiankov @ziyan

**Comment by cielavenir** [comment]
> openrave_FCL_LDFLAGS

that is equivalent of `openrave_bullet_CFLAGS_OTHER` in the link code.

**Comment by cielavenir** [comment]
> as #708 is taking too much time, I fixed this branch's CMAKE_REQUIRED_FLAGS.
> 
> there are two approaches to convert list to string:
> 
> * use string(REPLACE) #640
> * use [bulletrave-style](https://github.com/rdiankov/openrave/blob/master/plugins/bulletrave/CMakeLists.txt#L23) string concatenation #708
> 
> which do you like better?

@rdiankov @ziyan May I have comments on this?

**Comment by cielavenir** [comment]
|fcl.pc|fclrave CMakeLists|result|
|:--|:--|:--|
|-lfcl|FCL_LDFLAGS quoted|no problem|
|-lfcl|FCL_LDFLAGS unquoted|cmake fails|
|-lfcl|FCL_LDFLAGS string-ized|no problem|
|-L${libdir} -lfcl|FCL_LDFLAGS quoted|ninja fails, make ok|
|-L${libdir} -lfcl|FCL_LDFLAGS unquoted|no problem|
|-L${libdir} -lfcl|FCL_LDFLAGS string-ized|no problem|

our current configuration is (4). Woody changed the configuration to (5), but falls to (2) in some environments.

The pull request will change it to (6). (3) is also safe.

**Comment by cielavenir** [comment]
> How is this working until now?

because we are not using ninja.

**Comment by cielavenir** [comment]
@ziyan

**Comment by cielavenir** [comment]
how is this MR going

**Comment by rdiankov** [comment]
thanks

**Pull request merged**
