### PR TITLE
add backward compatibility for RaveOrientedBox deserialization

### PR DESCRIPTION
**Pull request by eisoku9618**
In the past, RaveOrientedBox was serialized with `halfExtents` / `pose` keywords.

### CODE REVIEW

**Comment by rdiankov** [comment]
I just noticed this. If possible, let's serialize to halfExtents, that is more standard

**Comment by cielavenir** [comment]
@eisoku9618 that scene was ok to load.

**Review by lazydroid — APPROVED** [review]
looks ok, thanks!

**Comment by cielavenir** [comment]
@eisoku9618 sorry, this pull request is blocking testplanningcommon. Please talk with @yoshikikanemoto (and @kanbouchou) for serialization format.

**Review by yoshikikanemoto — APPROVED** [review]

**Comment by yoshikikanemoto** [comment]
@rdiankov there was old scenes that use "pose" and "halfExtents" instead of "transform" and "extents". this change is just to support loading those old scenes.

**Comment by cielavenir** [comment]
@yoshikikanemoto so we will use "transform" and "extents" as default. Thank you for clarification.

**Review by cielavenir — APPROVED** [review]

**Comment by eisoku9618** [comment]
> If possible, let's serialize to halfExtents, that is more standard

Since many code use `extents` e.g. RaveOrientedBox / RaveAxisAlignedBox / PyOrientedBox / PyAABB so it takes some time to change all of them to `halfExtents`... :cry:

**Comment by cielavenir** [comment]
I agree that the C++ variable name and the serialization key should be the same.

**Comment by rdiankov** [comment]
Geometry already serializes to "halfExtents", so let's be consistent with the serialization, even if the variable names are not:
```c++
    case GT_Box:
        orjson::SetJsonValueByKey(rGeometryInfo, "halfExtents", _vGeomData*fUnitScale, allocator);
        break;
```

**Comment by eisoku9618** [comment]
test failed. checking.

**Comment by eisoku9618** [comment]
@rdiankov Could you review this MR again? We also need to merge one internal repository together with this change.

Pipeline #579072

**Comment by rdiankov** [comment]
thanks~

**Pull request merged**
