### PR TITLE
release GIL before potentially heavy computations

### PR DESCRIPTION
**Pull request by yoshikikanemoto**
so that other python threads can make progresses

### CODE REVIEW

**Comment by yoshikikanemoto** [comment]
tested on one actual system and AutoTester Pipeline #727062

**Comment by rdiankov** [comment]
One concern is that unlocking Gil for small operations might waste more CPU cycles. For example, are you sure Init function does enough computation?

**Comment by yoshikikanemoto** [comment]
> One concern is that unlocking Gil for small operations might waste more CPU cycles. For example, are you sure Init function does enough computation?

I checked my profiling result again. `KinBody::InitFromGeometries` was indeed taking time so I am sure. But I think we can assume `InitFromBoxes` / `InitFromSpheres` would finish fast. so i removed GIL unlock from there.

**Comment by yoshikikanemoto** [comment]
> > One concern is that unlocking Gil for small operations might waste more CPU cycles. For example, are you sure Init function does enough computation?
> 
> I checked my profiling result again. `KinBody::InitFromTriMesh` was indeed taking time so I am sure. But I think we can assume `InitFromBoxes` / `InitFromSpheres` would finish fast. so i removed GIL unlock from there.

Actually, `KinBody::InitFromTriMesh` was taking time on converting Python type to C++ type so unlocking GIL won't make a difference. I'll make another change.

**Comment by yoshikikanemoto** [comment]
> Actually, `KinBody::InitFromTriMesh` was taking time on converting Python type to C++ type so unlocking GIL won't make a difference. I'll make another change.

done @rdiankov

**Comment by rdiankov** [comment]
thanks~

**Pull request merged**
