### PR TITLE
Add input checks to _ComputeConvexHull and redirect QHull error messages to OpenRAVE log

### PR DESCRIPTION
**Pull request by woodychow**
Without the checks, the code will crash

### CODE REVIEW

**Comment by woodychow** [comment]
The following input checks are added

nan
points.size() > 0
dim >= 2

Also, QHull error messages are now redirected to the log.

**Comment by rdiankov** [comment]
thanks!
can we remove the nan check? probably system won't segfault if it is nan anyway...

**Comment by woodychow** [comment]
Done

**Comment by rdiankov** [comment]
thanks!
by the way, if you are going to output errfile, you should probably clear it everytime before you make the qhull call or you'll be displaying old results (same goes for outfile if you do output it)

**Comment by woodychow** [comment]
I was assuming that if exit code == 0, nothing will be written to errfile. That is probably true but I will change the code.

**Comment by rdiankov** [comment]
awesome!

**Comment by woodychow** [comment]
thanks!

**Pull request merged**
