### PR TITLE
Fix impersistent connected body joint vel/accel/etc limits

### PR DESCRIPTION
**Pull request by Puttichai**
### Background

Scaling of a robot's joint velocity/acceleration limits is a common operation during planning. However, when scaling the limits of robot joints that are coming from a connected body, the altered limits get reset every time when the robot is removed from the environment or when the environment is saved to a file.

```python
In [1]: cb = robot.GetConnectedBodies()[1]

In [2]: connectedBodyJointIndices = [joint.GetDOFIndex() for joint in cb.GetResolvedJoints() if joint.IsActive()]

In [3]: robot.GetDOFVelocityLimits(connectedBodyJointIndices)
Out[3]: array([0.72, 0.72, 0.72, 0.72, 0.72, 0.72, 0.72, 0.72])

In [4]: robot.SetDOFVelocityLimits(zeros(robot.GetDOF()))

In [5]: env.Remove(robot)
Out[5]: True

In [6]: env.Add(robot)

In [7]: robot.GetDOFVelocityLimits(connectedBodyJointIndices)
Out[7]: array([0.72, 0.72, 0.72, 0.72, 0.72, 0.72, 0.72, 0.72]) # expecting zeros
```

This is because there are two sources of information on robot joints: `robot._vecjoints` and `connectedBody._info._vJointInfos`. When, for example, setting new robot joint velocity limits via `robot.SetDOFVelocityLimits`, the information in `robot._vecjoints` changes but the information in `connectedBody._info` stays intact.

### Changes

A connected body's `_info` will now get updated whenever robot joint (position/velocity/etc.) limits change via a `ChangeCallback` registered to the robot. This way, `_info` can stay up to date at all times.

### CODE REVIEW

**Comment by rdiankov** [comment]
@cielavenir can you test this for regressions? thanks

**Comment by rdiankov** [comment]
@Puttichai can you update changelog/version?

**Comment by cielavenir** [comment]
For reasons I cannot help this.

@ntohge please take over this

**Comment by cielavenir** [comment]
I suppose this branch has been repeatedly tested in latest_test pipelines and in morning test cycles.

cc @ntohge @yoshikikanemoto

**Comment by rdiankov** [comment]
thanks~

**Pull request merged**
