### PR TITLE
Fixed document generation

### PR DESCRIPTION
**Pull request by cielavenir**
https://pybind11.readthedocs.io/en/stable/classes.html#dynamic-attributes

~~NOTE: THIS IS DRAFT, py::dynamic_attr SHOULD BE AVOIDED.~~ avoided done.

@felixvd

### CODE REVIEW

**Comment by rdiankov** [comment]
not sure i like this..

**Comment by cielavenir** [comment]
@felixvd With the current state, `make` will work (with preparing ikfaststats.pp) but please find a way to run openrave.py shell-block while openrave python3 dir symlinked.

**Comment by cielavenir** [comment]
@felixvd one my idea is https://github.com/rdiankov/openrave/pull/1250

**Comment by cielavenir** [comment]
@felixvd sorry I have to break this branch. c4d538c is known to work.

The error message is:

```
Traceback (most recent call last):py/databases.convexdecomposition                                                                                                                                                 
  File "/home/mujin/mujin/jhbuildappcontroller/install/bin/openrave.py", line 52, in <module>
    import openravepy
  File "/home/mujin/mujin/checkoutroot/openrave/docs/openravepy/__init__.py", line 31, in <module>
    from .openravepy_int import *
ImportError: /home/mujin/mujin/checkoutroot/openrave/docs/openravepy/openravepy_int.so: undefined symbol: PyInstanceMethod_Type
```

It can be fixed after merging #1250

**Comment by cielavenir** [comment]
@rdiankov by the way, could you add @felixvd to the members of rdiankov:openrave?

**Comment by cielavenir** [comment]
@felixvd now `make -C docs` is passing!

**Comment by cielavenir** [comment]
I removed dynamic_attr, it should be ok now

**Comment by cielavenir** [comment]
@felixvd please check

**Comment by felixvd** [comment]
I confirm that the command finishes, but the doc seems to have some issues:

- `robots.html` is not generated, so the link in the "Getting Started" section is dead
- I can't click on links in the frame on the right for some reason. 

There are also a lot of warnings (images not found etc). Some of them may have existed for a long time and can be ignored, but we should go through them and confirm.

**Comment by cielavenir** [comment]
@felixvd Forgot to add docs/robots symlink. I pushed it. Could you try again?

**Comment by cielavenir** [comment]
> I can't click on links in the frame on the right for some reason.

Can remove div.documentwrapper's "float: left;" from build/en/sphinxhtml/_static/sphinxdoc.css, but I don't know the correct way.

@felixvd It builds, so I think you can continue, right?

@rdiankov Could you give the push right to Felix?

**Comment by rdiankov** [comment]
thanks~

**Pull request merged**
