### PR TITLE
Use pickle protocol 2

### PR DESCRIPTION
**Pull request by cielavenir**
because it is more efficient

### CODE REVIEW

**Comment by rdiankov** [comment]
@cielavenir let's also update the versions of the databases so we force re-generation

**Comment by cielavenir** [comment]
https://pybind11.readthedocs.io/en/stable/advanced/classes.html#pickling-support

**Comment by cielavenir** [comment]
ok let me update

**Comment by cielavenir** [comment]
well is https://github.com/rdiankov/openrave/pull/1089/commits/67343eea4d8489d6383627afaaeb9fb6e1ee2ec0 correct?

**Comment by rdiankov** [comment]
@cielavenir what about linkstatistics?
```
    def getversion(self):
        return 6
```

**Comment by cielavenir** [comment]
@rdiankov done

well should I revert 67343eea4 ?

**Comment by rdiankov** [comment]
@cielavenir we also have convexdecomposition.py

**Comment by rdiankov** [comment]
thanks~

**Pull request merged**
