### PR TITLE
Rename to jointControlInfo(RobotController|IO|ExternalDevice), basica…

### PR DESCRIPTION
**Pull request by ziyan**
…lly "jointControlInfo" + controlMode.

### CODE REVIEW

**Comment by felixvd** [comment]
This has my support

**Comment by braineo** [comment]
Looks much better IMO

**Comment by snozawa** [comment]
nice!

how about variable names?

if this PR is intended to change minimally, e.g. only change the naming exposed to the users, i think it's fine.
Thanks!

**Comment by ziyan** [comment]
> nice!
> 
> how about variable names?
> 
> if this PR is intended to change minimally, e.g. only change the naming exposed to the users, i think it's fine. Thanks!

The variable names are fine as-is. They can change over time, and compilation will check for correctness. The JSON names, however, are contracts that will be much much harder to change.

**Comment by snozawa** [comment]
> The variable names are fine as-is. They can change over time, and compilation will check for correctness. The JSON names, however, are contracts that will be much much harder to change.

i see, make sense!

**Pull request merged**
