### PR TITLE
Add new IkReturnAction type for rejected IK due to occlusion.

### PR DESCRIPTION
**Pull request by eisoku9618**

### CODE REVIEW

**Comment by cielavenir** [comment]
sent mattermost message

**Comment by eisoku9618** [comment]
There is a better place to put this change in our code base. Thank you @cielavenir

**Comment by cielavenir** [comment]
お手数おかけします

**Comment by rdiankov** [comment]
This doesn't belong in OpenRAVE

**Comment by cielavenir** [comment]
Now that Rosen replies, I disclose the content of my mattermost message: when I saw this, I remember https://github.com/rdiankov/openrave/pull/1136 and I suggested Eisoku to move the MR content to controllercommon.

And now I assigned you (Rosen) to controllercommon!655 merge request.

**Pull request closed without merging**
