### PR TITLE
Bullseye

### PR DESCRIPTION
**Pull request by ziyan**

### CODE REVIEW

**Comment by cielavenir** [comment]
@rdiankov actually merging https://github.com/rdiankov/openrave/pull/1019 into production as well is enough.

**Comment by ziyan** [comment]
> @rdiankov actually merging #1019 into production as well is enough.

Are these changes needed? I saw you are using them in the branch file @cielavenir

**Comment by cielavenir** [comment]
not needed but keeping production being superset of master is important

**Comment by rdiankov** [comment]
thanks~

**Pull request merged**
