### PR TITLE
Make fixes for OS X

### PR DESCRIPTION
**Pull request by yn**
The default homebrew openscenegraph installation doesn't package osgQt - that means that a compilation error happened prior to this PR, because the condition checks for OPENSCENEGRAPH only, not for OSGQT

On OS X, intl isn't part of the default C library, so some CMAKE fixes are in order to get that working.

### CODE REVIEW

**Comment by rdiankov** [comment]
YN, all your changes are good except  `#  set(PLUGINS ${PLUGINS} fclrave)`

We'll be pushing in a fix later today, so can you test afterwards?

thanks

**Comment by yn** [comment]
Will test as soon as I see you fix.

**Comment by rdiankov** [comment]
just pushed a fix, can you double check? thanks

**Comment by yn** [comment]
I reverted the part where I comment out fclrave. I think you can merge this PR now. As I mentioned in #419, FCL still errors out, but that seems like a separate issue, so let's address it separately.

**Comment by rdiankov** [comment]
thanks!
we're resolving the fcl issue right now, but that is separate from your commits.

**Pull request merged**
