### PR TITLE
cmake: Add support to build Python 3 in parallel to Python 2

### PR DESCRIPTION
**Pull request by undisputed-seraphim**
Just enough changes to CMake that allows us to build Python 3 bindings at the same time alongside Python 2 bindings.

- Enable with `OPT_PYTHON3` flag. Defaults to 'ON'.
- Backward compatibility is kept. Defaults to Python 2.
- Variables exported in CMake default to Python 2
- Python 3 variants of CMake variables have a '3' after any 'PYTHON' word in its name, e.g. `OpenRAVE_USE_PYBIND11_PYTHON3_BINDINGS`

For more information, check the changes to the file `openrave-config.cmake.in`.

cc @cielavenir 

Pipeline #483845

### CODE REVIEW

**Comment by cielavenir** [comment]
- `/opt/lib/python3.9/site-packages/openravepy/` is missing `__init__.py` and `_openravepy_` symlink to `_openravepy_0_106`
- Please do not rename _openravepy_0_106 to _openravepy3_0_106
- `/opt/lib/python3.9/site-packages/openravepy/_openravepy_0_106/` does not have plugins
- `/opt/lib/python3.9/site-packages/openravepy/_openravepy_0_106/` does not have databases etc
- openravepy_int.so is renamed to openravepy3_int.so and others are similar. Please avoid that.

**Comment by undisputed-seraphim** [comment]
>     * openravepy_int.so is renamed to openravepy3_int.so and others are similar. Please avoid that.

What naming convention do you recommend?

**Comment by cielavenir** [comment]
> What naming convention do you recommend?

literally `/opt/lib/python3.9/site-packages/openravepy/_openravepy_0_106/openravepy_int.so`

**Comment by undisputed-seraphim** [comment]
Pipeline #483996

**Comment by cielavenir** [comment]
I need to clarify that we have to prepare openravepy.Environment on Py3 without interfering our current workflow, before china team's discussion about mujinsimulator.

**Comment by cielavenir** [comment]
@undisputed-seraphim 

```
root@62dad5a573f7:/# ls /opt/lib/python3.9/site-packages/openravepy/_openravepy_0_106/
convexdecompositionpy.so	  ikfast.h	      metaclass.py			      openravepy_ext.py			  openravepy_piecewisepolynomials.so.debug  pyANN_int.so.debug
convexdecompositionpy.so.debug	  ikfast.py	      misc.py				      openravepy_int.so			  openravepy_rampoptimizer.so		    pyANN.py
ikfast_generator_cpp.py		  ikfast_sympy0_6.py  openravepy_configurationcache.so	      openravepy_int.so.debug		  openravepy_rampoptimizer.so.debug	    __pycache__
ikfast_generator_cpp_sympy0_6.py  __init__.py	      openravepy_configurationcache.so.debug  openravepy_piecewisepolynomials.so  pyANN_int.so				    trajectoryutils.py
root@62dad5a573f7:/# ls /opt/lib/python2.7/site-packages/openravepy/_openravepy_0_106/
convexdecompositionpy.so	  ikfast.h	      metaclass.py			      openravepy_ext.py				openravepy_rampoptimizer.so	   trajectoryutils.py
convexdecompositionpy.so.debug	  ikfast.py	      metaclass.pyc			      openravepy_ext.pyc			openravepy_rampoptimizer.so.debug
databases			  ikfast_sympy0_6.py  misc.py				      openravepy_int.so				pyANN_int.so
examples			  __init__.py	      misc.pyc				      openravepy_int.so.debug			pyANN_int.so.debug
ikfast_generator_cpp.py		  __init__.pyc	      openravepy_configurationcache.so	      openravepy_piecewisepolynomials.so	pyANN.py
ikfast_generator_cpp_sympy0_6.py  interfaces	      openravepy_configurationcache.so.debug  openravepy_piecewisepolynomials.so.debug	pyANN.pyc
```

databases / examples / interfaces are missing from python3.9

other parts looks ok

**Comment by undisputed-seraphim** [comment]
Pipeline #484216

**Review by cielavenir — APPROVED** [review]

**Comment by cielavenir** [comment]
thank you!

**Review by lazydroid — APPROVED** [review]
The latest pipeline ran clean, looks good to merge!

Pipeline #484339

**Comment by rdiankov** [comment]
thanks~

**Comment by cielavenir** [comment]
@undisputed-seraphim openrave-config had to be updated: https://github.com/rdiankov/openrave/pull/1249

**Pull request merged**
