### PR TITLE
Migrate from boost::numeric to boost:numpy for Boost 1.6x

### LINKED ISSUE #551: Python modules do not build against Boost.Python>1.65.1
Building with Boost.Python version 1.65.1 or greater is broken, as the `boost::python::numeric` namespace has been removed in favor of `boost::python::numpy`. See [version notes](http://www.boost.org/users/history/version_1_65_1.html).

### PR DESCRIPTION
**Pull request by morxa**
Adapt the code base to Boost 1.6x:
* Replace every `boost::numeric::array` by `boost::numpy::array`
* Use `boost::numpy::ndarray` instead of `PyArray`
* Adapt and rewrite parts of `PyTriMesh` constructor and its `GetTriMesh` function
* Remove no longer needed `AutoPyArrayObjectDereferencer`

This fixes #551.

### CODE REVIEW

**Comment by morxa** [comment]
This also fixes #542.

**Comment by stephane-caron** [comment]
Tried this PR today to install OpenRAVE on Ubuntu 18.04 whose Boost version is 1.65.

It compiles fine, however robot functions that should return a vector, like ``robot.GetDOFValues()``, fail with a TypeError exception:

```python
In [2]: robot
Out[2]: RaveGetEnvironment(1).GetRobot('JVRC-1')

In [3]: robot.GetDOF()
Out[3]: 50

In [4]: robot.GetDOFValues()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-b710d87c980c> in <module>()
----> 1 robot.GetDOFValues()

TypeError: 'int' object is not iterable

In [5]: robot.GetDOFVelocities()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-b710d87c980c> in <module>()
----> 1 robot.GetDOFVelocities()

TypeError: 'int' object is not iterable
```

Any idea where this could come from?

**Comment by cielavenir** [comment]
It seems just typo. I fixed in https://github.com/cielavenir/openrave/commit/b983e27178826b863bd2932613b4f41ad472a129 and prepared something compilable on Ubuntu bionic in https://github.com/cielavenir/openrave/tree/boost-1.6x

**Comment by morxa** [comment]
@rdiankov any chance you will have a look at this at any time soon? If not, please close the PR. Thanks!

**Comment by lianghongzhuo** [comment]
I'm trying to Migrate from boost::numeric toboost:numpy for Boost too. As your pull request's  is outdated and has conflicts that must be resolved.
In the current master branch rdiankov/openrave@811cf23 I finished most cases by replace numeric::array to numpy::ndarray
But I stuck at here https://github.com/rdiankov/openrave/blob/master/python/bindings/include/openravepy/boostpython/boostpython_bindings.h#L23-L25
any suggestion on how to change these lines?

**Comment by morxa** [comment]
> any suggestion on how to change these lines?

No.

This pull request is obsolete, it looks like a different approach was taken.

**Pull request closed without merging**
