### PR TITLE
fix log message in plugins/configurationcache/configurationjitterer.cpp

### PR DESCRIPTION
**Pull request by y423610m**
Fix log message related to jittering.

### CODE REVIEW

**Comment by rdiankov** [comment]
Thanks

**Comment by kanbouchou** [comment]
@y423610m could you make another PR targeting to `production` branch? That is the default branch.

**Comment by y423610m** [comment]
@kanbouchou Sorry for my mistake. I recreated [PR](https://github.com/rdiankov/openrave/pull/1352).

**Comment by cielavenir** [comment]
I feel sorry; I have suggested to change the github default branch to production via https://github.com/rdiankov/openrave/settings , but that page can be accessed only by Rosen..

**Pull request merged**
