### PR TITLE
Fix ExtractAll not returning removed bodies, and also grabbed update …

### PR DESCRIPTION
**Pull request by ziyan**
…not using grabbedName.

### CODE REVIEW

**Comment by rdiankov** [comment]
@yoshikikanemoto @eisoku9618 can you review this? thanks

**Comment by yoshikikanemoto** [comment]
@rdiankov @ziyan looks good to me

**Comment by rdiankov** [comment]
thanks

**Comment by ziyan** [comment]
@yoshikikanemoto Thank you!

**Pull request merged**
