### PR TITLE
Set config.h OPENRAVE_PYTHON_EXECUTABLE

### PR DESCRIPTION
**Pull request by cielavenir**
LiBoon's change deleted PYTHON_EXECUTABLE variable, that was fine itself. But it turned out that it broke OPENRAVE_PYTHON_EXECUTABLE config.h, and plugins/ikfastsolvers/ikfastmodule.cpp stopped working.

_I guess_ we have tested AddIkLibrary codepath repeatedly but not  LoadIKFastSolver codepath.

```
2024-03-22 17:35:37,215 openrave [INFO] [ikfastmodule.cpp:682 _EnsureIkFastVersion] Getting ikfast version from existing python. OPENRAVE_PYTHON_EXECUTABLE=
sh: 1: -c: not found
2024-03-22 16:07:15,416 openrave [WARN] [ikfastmodule.cpp:616 LoadIKFastSolver] failed to find ikfile: kinematics.331f3d8a4304006d695f6f3cd9b319f1/ikfast.Transform6D..0_1_2_3_4_5.so
2024-03-22 16:07:15,416 openrave [ERROR] [binpickingmodule_compute.cpp:4420 binpickingmodule::BinPickingModule::_MoveManipJoints] env=6(pw_plan2), planrequest 1: failed to init plan because of openrave (Assert): [redacted] env=6(pw_plan2), failed to load 6D ik solver from 'ikfast' for manip '[redacted]_gripper_suction'
```

Reported by @DanyuanZhuo

/cc @ntohge

### CODE REVIEW

**Comment by rdiankov** [comment]
once we move to python3, will this need to change?

**Comment by cielavenir** [comment]
yes...

@DanyuanZhuo @osbertngok @liuhuanjim013 How do you think?

**Comment by cielavenir** [comment]
@rdiankov actually I changed to configure by CMakeLists. Now we dont need to change that part after moving to py3.

**Comment by osbertngok** [comment]
@cielavenir the new change looks reasonable to me; it would cater both Python2 and Python3. I assume we won't be dropping support for Python2 any time soon..

**Comment by cielavenir** [comment]
yes, lets merge

**Comment by rdiankov** [comment]
thanks

**Pull request merged**
