### PR TITLE
RaveAddCallbackForDestroy was getting called once per dae read/write.

### PR DESCRIPTION
**Pull request by ziyan**
Might be accumulating function pointers in _listDestroyCallbacks.

### CODE REVIEW

**Comment by rdiankov** [comment]
Hmm... whole point of having a RaveGlobal runtime is to remove dependency on static variables like this. You should have a way of confirming whether the current RaveGlobal supports this, perhaps have an id for the add/remove callback

**Comment by rdiankov** [comment]
i wonder if inside `AddCallbackForDestroy`, we can check if the function pointers are equal before adding it to `_listDestroyCallbacks`

**Comment by ziyan** [comment]
Unfortunately, comparing boost functions is not supported:

https://www.boost.org/doc/libs/1_70_0/doc/html/function/faq.html

**Comment by rdiankov** [comment]
ok, let's go with your idea of static bool. i added a different reset fn with locking to make it even more safe.
thanks~

**Comment by ziyan** [comment]
Oops, forgot to initialize `s_daedestroycallback` to `false`

**Pull request merged**
