### PR TITLE
inherit CMAKE_MODULE_PATH

### PR DESCRIPTION
**Pull request by cielavenir**
We want to specify CMAKE_MODULE_PATH externally

/cc @kktk-KO

### CODE REVIEW

**Comment by cielavenir** [comment]
The situation is the same as controllercommon/CMakeLists.txt:9

**Comment by cielavenir** [comment]
@rdiankov Takuya has issues around custom cmake module path.

**Comment by takuya-smz** [comment]
@rdiankov I have issues in overriding CMAKE_MODULE_PATH in .jhbuildrc

**Comment by rdiankov** [comment]
thanks

**Pull request merged**
