### PR TITLE
Optimize PadMesh function

### PR DESCRIPTION
**Pull request by woodychow**
Code is 7~8x faster on my computer.

### CODE REVIEW

**Comment by rdiankov** [comment]
cool, a minor suggestion:

- perhaps you can cache vertices[indices[:,INDEX]] and newvertices[newindices[:, INDEX]] so you don't look it up several times.

thanks

**Comment by woodychow** [comment]
I am not sure if that would help. From what I understand, those are just views of the original matrix. I don't believe creating the view will take much time at all. Let me do some experiments.

**Comment by woodychow** [comment]
Caching the view helps a tiny bit; perhaps the number of vertices is too small in my experiment. Anyhow, let's cache the views.

**Comment by rdiankov** [comment]
looks good, thanks!

**Pull request merged**
