### PR TITLE
Allow ikfast unavailable, existing solvers should be still usable

### PR DESCRIPTION
**Pull request by cielavenir**

### CODE REVIEW

**Comment by cielavenir** [comment]
pipeline: https://tiny.mujin.co.jp/u9ffu

**Comment by cielavenir** [comment]
well, https://github.com/rdiankov/openrave/pull/1391 is more clean (if it works...)

**Comment by rdiankov** [comment]
So is this MR mutually exclusive with #1391?

**Comment by rdiankov** [comment]
for now okay, thanks

**Comment by cielavenir** [comment]
> So is this MR mutually exclusive with https://github.com/rdiankov/openrave/pull/1391 ?

not exclusive

**Pull request merged**
