### PR TITLE
Maintain active geometry group name

### PR DESCRIPTION
**Pull request by eisoku9618**
So that `CollisionChecker.GetBodyGeometryGroup()` returns group name correctly. 
- `GetBodyGeometryGroup()` is supported only by fclrave so far, so I updated fclrave only and not oderave etc.
- pipelineid=416799

### CODE REVIEW

**Comment by eisoku9618** [comment]
I found an issue, so mark this as Draft.

**Comment by eisoku9618** [comment]
fixed

**Comment by kanbouchou** [comment]
@eisoku9618 this looks good, but is this still draft? can you update the status if you don't have any more change?

**Comment by kanbouchou** [comment]
@rdiankov could you review this together with application side change? Together with application side change, this improves geometry group switching time a lot.

**Comment by rdiankov** [comment]
thanks~

**Pull request merged**
