### PR TITLE
Increment startindex in GetTrajectorySegment function.

### PR DESCRIPTION
**Pull request by snozawa**
Increment startindex.
later on, we use startindex. but, if we 'Remove' the first point, corresponding 'startindex' should be incremented.

### CODE REVIEW

**Comment by snozawa** [comment]
- Problem
   if we use good-cut value for `starttime` such as multiple of deltatime, it  does not work.
    ```
   openrave_exception: openrave (Assert): [OpenRAVE::TrajectoryBasePtr OpenRAVE::planningutils::GetTrajectorySegment(OpenRAVE::TrajectoryBaseConstPtr, OpenRAVE::dReal, OpenRAVE::dReal):1890] RaveFabs(outtraj->GetDuration() - (endtime - starttime)) <= g_fEpsilonLinear*traj->GetNumWaypoints(), (eval 0.1 <= 1.58114e-13) 
    ```

- How to solve
    in the if sentence if we use good-cut value, we use `Remove` and it seems inconsistent with later computation.
    Just increment the `startindex`.


- test code (without this PR, this test code fails)
    ```
    import openravepy
    newtraj = openravepy.RaveCreateTrajectory(robot.GetEnv(),'')
    posspec = robot.GetActiveConfigurationSpecification('linear')
    posspec.AddDeltaTimeGroup()
    newtraj.Init(posspec)
    dt = 0.1
    newtraj.Insert(0, numpy.hstack([[0]*robot.GetDOF() + [dt]]))
    newtraj.Insert(0, numpy.hstack([[0]*robot.GetDOF() + [dt]]))
    newtraj.Insert(0, numpy.hstack([[0]*robot.GetDOF() + [dt]]))
    newtraj.Insert(0, numpy.hstack([[0]*robot.GetDOF() + [dt]]))
    newtraj.Insert(0, numpy.hstack([[0]*robot.GetDOF() + [0]]))
    duration = newtraj.GetDuration()

    # Call GetTrajectorySegment for different start/end times
    eps = 1e-9
    startTimeList = [0, eps, dt*0.5, dt-eps, dt+eps, dt*0.5+dt, 2*dt-eps, 2*dt, 2*dt+eps]
    endTimeList = [duration, duration-eps, duration-dt]
    for startTime in startTimeList:
        for endTime in endTimeList:
            log.warn('startTime=%r, endTime=%r', startTime, endTime)
            openravepy.planningutils.GetTrajectorySegment(newtraj, startTime, endTime)
    ```

**Comment by rdiankov** [comment]
wow, yes, that was pretty silly mistake.
although your fix is correct, i'm wondering whether we should do the following instead:
```c++
        outtraj->Sample(values, endtime-starttime);
        outtraj->Insert(outtraj->GetNumWaypoints()-1,values,true); // assume last end point
```

what do you think?

**Comment by snozawa** [comment]
oh, i see.
it is much more understandable!
i reflected your comment to this PR.
i also confirmed that the above test code passed with the new PR.

**Comment by rdiankov** [comment]
thanks!

**Pull request merged**
