### PR TITLE
Parse FCL_LDFLAGS

### PR DESCRIPTION
**Pull request by cielavenir**
Since we already have used the technique in bulletrave, why don't we use it also in fclrave? And I updated bulletrave comment as well.

As current origin/master and origin/production are the same, it is up to you which to merge.

Note: if this is merged, please close #640

### CODE REVIEW

**Comment by rdiankov** [comment]
does `"${PLUGIN_LINK_FLAGS}" ${FCL_LDFLAGS}`work?

**Comment by cielavenir** [comment]
@rdiankov I confirmed that would cause #633 if /usr/local/lib/pkgconfig/fcl.pc's Libs is only `-lfcl`. Usual fcl.pc.in has Libs `-L${libdir} -lfcl`, so we were not aware the corner case.

**Comment by cielavenir** [comment]
#795 appeared...

**Comment by cielavenir** [comment]
closing this one

**Pull request closed without merging**
