### PR TITLE
Environment::drawarray() to visualize a list of boxes

### PR DESCRIPTION
**Pull request by ompugao**
This is useful to visualize voxels efficiently in an openrave environment.
Calling Environment::drawbox many times results in slow framerate and buggy behavior in qtosg.

### CODE REVIEW

**Comment by rdiankov** [comment]
@ompugao awesome! can you bump the minor version of openrave since ABI changes?

**Comment by ompugao** [comment]
thank you for your check.
I bumped up the minor version.

**Comment by ompugao** [comment]
ping

**Comment by rdiankov** [comment]
woot, thanks~

**Pull request merged**
