### PR TITLE
Add optional `uri` argument for LoadJSON and add ReadRobotJSON and ReadKinBodyJSON

### PR DESCRIPTION
**Pull request by superfashi**
This PR adds optional `uri` argument for `LoadJSON`.

It also adds `ReadRobotJSON` and `ReadKinBodyJSON` for completion.

### CODE REVIEW

**Comment by rdiankov** [comment]
The mechanics of `ReadRobotJSON` and `ReadKinBodyJSON` are not consistent with the other Read functions. For some reason, your implementation requires the parts to be already added to the environment.

**Comment by rdiankov** [comment]
> The mechanics of `ReadRobotJSON` and `ReadKinBodyJSON` are not consistent with the other Read functions. For some reason, your implementation requires the parts to be already added to the environment.

Particularly, why is the following code necessary if the body is not in the environment:
```
+            FOREACH(itviewer, _listViewers) {
+                (*itviewer)->RemoveKinBody(robot);
+            }
```

**Comment by superfashi** [comment]
> > The mechanics of `ReadRobotJSON` and `ReadKinBodyJSON` are not consistent with the other Read functions. For some reason, your implementation requires the parts to be already added to the environment.
> 
> Particularly, why is the following code necessary if the body is not in the environment:
> 
> ```
> +            FOREACH(itviewer, _listViewers) {
> +                (*itviewer)->RemoveKinBody(robot);
> +            }
> ```

This part of code I just simply copied from other `Read[Type]` functions. https://github.com/rdiankov/openrave/blame/production/src/libopenrave-core/environment-core.h#L1747-L1757

About the implementation requires the parts to be already added to the environment, that should not be true. I tested and it can parse with empty environment.

**Comment by rdiankov** [comment]
@superfashi if `uri` is empty, did you test that the loaded objec'ts GetURI returns just "#XXX"?

**Review by superfashi — COMMENTED** [review]
revert bed025c2

**Comment by rdiankov** [comment]
thanks~

**Pull request merged**
