### PR TITLE
Skybox

### PR DESCRIPTION
**Pull request by braineo**
Add skybox for qtosgviewer

Given six textures it can construct a skybox following the camera

### CODE REVIEW

**Comment by rdiankov** [comment]
can you comment on why you added:


`
set(LIBOPENRAVE_LINK_FLAGS "-ldl -pthread") 
`



thanks

**Comment by braineo** [comment]
@rdiankov  compilation stops and saying not able to find reference of pthread before linking for me. Maybe it is not necessary for others.

**Comment by rdiankov** [comment]
please show me the linking error on your machine
thanks

**Comment by braineo** [comment]
I get this error
```
*** Building openrave *** [38/129]
make -j4 
[  0%] Built target openrave-md5
[  1%] Built target openrave-md5-native
[ 10%] Built target crlibm-native
[ 19%] Built target crlibm
Scanning dependencies of target fparser
[ 21%] Built target minizip
[ 25%] Built target ANN
[ 25%] Built target ivcon
[ 26%] Building CXX object 3rdparty/fparser-4.5/CMakeFiles/fparser.dir/fparser.cc.o
[ 29%] Built target locale
[ 30%] Built target check_libm_accuracy-native
[ 33%] Built target convexdecomposition
[ 34%] Built target pyANN_int
[ 36%] Built target PQP
[ 38%] Built target cpp-gen-md5-native
[ 39%] Built target convexdecompositionpy
Scanning dependencies of target interfacehashes_target
[ 40%] Built target interfacehashes_target
[ 42%] Built target rampoptimizer
[ 43%] Linking CXX static library libfparser.a
[ 43%] Built target fparser
Scanning dependencies of target libopenrave
[ 43%] Building CXX object src/libopenrave/CMakeFiles/libopenrave.dir/kinbodyjoint.cpp.o
[ 43%] Linking CXX shared library libopenrave0.9.so
[ 49%] Built target libopenrave
[ 49%] Linking CXX shared library libopenrave0.9_c.so
[ 49%] Linking CXX shared library libbaserobots.so
[ 50%] Linking CXX shared library libbasecontrollers.so
[ 50%] Linking CXX shared library libopenrave0.9-core.so
[ 51%] Built target libopenrave_c
[ 51%] Linking CXX shared library libbasesamplers.so
[ 52%] Built target baserobots
[ 52%] Linking CXX shared library libbasesensors.so
[ 53%] Built target basecontrollers
[ 54%] Linking CXX shared library libconfigurationcache.so
[ 56%] Built target basesamplers
[ 56%] Linking CXX shared library libdualmanipulation.so
[ 56%] Built target basesensors
[ 57%] Linking CXX shared library libgrasper.so
[ 57%] Built target dualmanipulation
[ 57%] Linking CXX shared library libikfastsolvers.so
[ 58%] Built target configurationcache
[ 58%] Linking CXX shared library liblogging.so
[ 58%] Built target grasper
[ 58%] Linking CXX shared library libpqprave.so
[ 59%] Built target logging
[ 59%] Linking CXX shared library librmanipulation.so
[ 60%] Built target pqprave
[ 62%] Built target ParabolicPathSmooth
[ 62%] Linking CXX shared library libtextserver.so
[ 63%] Built target textserver
[ 63%] Generating moc_qtosgviewer.cxx
[ 65%] Built target rmanipulation
[ 66%] Linking CXX shared library libqtcoinrave.so
[ 71%] Built target ikfastsolvers
[ 72%] Linking CXX shared library liboderave.so
[ 77%] Built target libopenrave-core
[ 77%] Linking CXX shared library libfclrave.so
[ 77%] Built target oderave
[ 77%] Linking CXX executable openrave0.9
Scanning dependencies of target qtosgrave
[ 78%] Built target fclrave
libopenrave-core/libopenrave0.9-core.so.0.9.0: error: undefined reference to 'pthread_mutexattr_init'
libopenrave-core/libopenrave0.9-core.so.0.9.0: error: undefined reference to 'pthread_mutexattr_settype'
libopenrave-core/libopenrave0.9-core.so.0.9.0: error: undefined reference to 'pthread_mutexattr_destroy'
libopenrave-core/libopenrave0.9-core.so.0.9.0: error: undefined reference to 'pthread_mutex_timedlock'
libopenrave-core/libopenrave0.9-core.so.0.9.0: error: undefined reference to 'pthread_mutex_trylock'
libopenrave/libopenrave0.9.so.0.9.0: error: undefined reference to 'dlerror'
libopenrave/libopenrave0.9.so.0.9.0: error: undefined reference to 'dlsym'
libopenrave/libopenrave0.9.so.0.9.0: error: undefined reference to 'dlclose'
libopenrave/libopenrave0.9.so.0.9.0: error: undefined reference to 'dlopen'
libopenrave/libopenrave0.9.so.0.9.0: error: undefined reference to 'dladdr'
collect2: error: ld returned 1 exit status
make[2]: *** [src/openrave0.9] Error 1
make[1]: *** [src/CMakeFiles/openrave.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 78%] Linking CXX shared library libopenrave0.9-core_c.so
[ 78%] Building CXX object plugins/qtosgrave/CMakeFiles/qtosgrave.dir/moc_qtosgviewer.cxx.o
[ 78%] Building CXX object plugins/qtosgrave/CMakeFiles/qtosgrave.dir/qtosgviewer.cpp.o
[ 79%] Built target libopenrave-core_c
[ 81%] Built target qtcoinrave
[ 81%] Linking CXX shared library libqtosgrave.so
[ 86%] Built target qtosgrave
```

**Comment by rdiankov** [comment]
ok, i pushed all the changes except the link flags.

**Pull request merged**
